// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseConsole.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230209175822_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Id", "AccountId");

                    b.ToTable("account_character");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountId = 1L,
                            Armor = 0,
                            DateCreated = new DateTime(2023, 2, 9, 14, 58, 22, 109, DateTimeKind.Local).AddTicks(9757),
                            Gender = 0,
                            Model = "mp_m_freemode_01",
                            Name = "Admin",
                            Slot = 0,
                            Surname = "Thalys"
                        });
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedComponentModel", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("Texture")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "ComponentId");

                    b.ToTable("account_character_ped_component");

                    b.HasData(
                        new
                        {
                            CharacterId = 1L,
                            ComponentId = 0,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            ComponentId = 1,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            ComponentId = 2,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            ComponentId = 3,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            ComponentId = 4,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            ComponentId = 5,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            ComponentId = 6,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            ComponentId = 7,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            ComponentId = 8,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            ComponentId = 9,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            ComponentId = 10,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            ComponentId = 11,
                            Index = 0,
                            Texture = 0
                        });
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedFaceModel", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<float>("Scale")
                        .HasColumnType("float");

                    b.HasKey("CharacterId", "Index");

                    b.ToTable("account_character_ped_face");

                    b.HasData(
                        new
                        {
                            CharacterId = 1L,
                            Index = 0,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 1,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 2,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 3,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 4,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 5,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 6,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 7,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 8,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 9,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 10,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 11,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 12,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 13,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 14,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 15,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 16,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 17,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 18,
                            Scale = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            Index = 19,
                            Scale = 0f
                        });
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedHeadDataModel", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsParent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ShapeFirstID")
                        .HasColumnType("int");

                    b.Property<float>("ShapeMix")
                        .HasColumnType("float");

                    b.Property<int>("ShapeSecondID")
                        .HasColumnType("int");

                    b.Property<int>("ShapeThirdID")
                        .HasColumnType("int");

                    b.Property<int>("SkinFirstID")
                        .HasColumnType("int");

                    b.Property<float>("SkinMix")
                        .HasColumnType("float");

                    b.Property<int>("SkinSecondID")
                        .HasColumnType("int");

                    b.Property<int>("SkinThirdID")
                        .HasColumnType("int");

                    b.Property<float>("ThirdMix")
                        .HasColumnType("float");

                    b.HasKey("CharacterId");

                    b.ToTable("account_character_ped_head_data");

                    b.HasData(
                        new
                        {
                            CharacterId = 1L,
                            IsParent = false,
                            ShapeFirstID = 0,
                            ShapeMix = 0f,
                            ShapeSecondID = 0,
                            ShapeThirdID = 0,
                            SkinFirstID = 0,
                            SkinMix = 0f,
                            SkinSecondID = 0,
                            SkinThirdID = 0,
                            ThirdMix = 0f
                        });
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedHeadModel", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<int>("EyeColorId")
                        .HasColumnType("int");

                    b.Property<int>("HairColorId")
                        .HasColumnType("int");

                    b.Property<int>("HairHighlightColor")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.ToTable("account_character_ped_head");

                    b.HasData(
                        new
                        {
                            CharacterId = 1L,
                            EyeColorId = 0,
                            HairColorId = 0,
                            HairHighlightColor = 0
                        });
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedHeadOverlayColorModel", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<int>("OverlayId")
                        .HasColumnType("int");

                    b.Property<int>("ColorType")
                        .HasColumnType("int");

                    b.Property<int>("ColortId")
                        .HasColumnType("int");

                    b.Property<int>("SecondColorId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "OverlayId");

                    b.ToTable("account_character_ped_head_overlay_color");
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedHeadOverlayModel", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<int>("OverlayId")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<float>("Opacity")
                        .HasColumnType("float");

                    b.HasKey("CharacterId", "OverlayId");

                    b.ToTable("account_character_ped_head_overlay");

                    b.HasData(
                        new
                        {
                            CharacterId = 1L,
                            OverlayId = 0,
                            Index = 0,
                            Opacity = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            OverlayId = 1,
                            Index = 0,
                            Opacity = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            OverlayId = 2,
                            Index = 0,
                            Opacity = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            OverlayId = 3,
                            Index = 0,
                            Opacity = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            OverlayId = 4,
                            Index = 0,
                            Opacity = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            OverlayId = 5,
                            Index = 0,
                            Opacity = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            OverlayId = 6,
                            Index = 0,
                            Opacity = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            OverlayId = 7,
                            Index = 0,
                            Opacity = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            OverlayId = 8,
                            Index = 0,
                            Opacity = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            OverlayId = 9,
                            Index = 0,
                            Opacity = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            OverlayId = 10,
                            Index = 0,
                            Opacity = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            OverlayId = 11,
                            Index = 0,
                            Opacity = 0f
                        },
                        new
                        {
                            CharacterId = 1L,
                            OverlayId = 12,
                            Index = 0,
                            Opacity = 0f
                        });
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedPropModel", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<int>("PropId")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("Texture")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "PropId");

                    b.ToTable("account_character_ped_prop");

                    b.HasData(
                        new
                        {
                            CharacterId = 1L,
                            PropId = 0,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            PropId = 1,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            PropId = 2,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            PropId = 3,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            PropId = 4,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            PropId = 5,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            PropId = 6,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            PropId = 7,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            PropId = 8,
                            Index = 0,
                            Texture = 0
                        },
                        new
                        {
                            CharacterId = 1L,
                            PropId = 9,
                            Index = 0,
                            Texture = 0
                        });
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPositionModel", b =>
                {
                    b.Property<long>("ChatacterId")
                        .HasColumnType("bigint");

                    b.Property<float>("X")
                        .HasColumnType("float");

                    b.Property<float>("Y")
                        .HasColumnType("float");

                    b.Property<float>("Z")
                        .HasColumnType("float");

                    b.HasKey("ChatacterId");

                    b.ToTable("account_character_position");

                    b.HasData(
                        new
                        {
                            ChatacterId = 1L,
                            X = 0f,
                            Y = 0f,
                            Z = 0f
                        });
                });

            modelBuilder.Entity("Shared.Models.Database.AccountModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("License")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("WhiteListed")
                        .HasColumnType("tinyint(1)")
                        .HasMaxLength(1);

                    b.HasKey("Id");

                    b.HasIndex("Id", "License");

                    b.ToTable("account");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Created = new DateTime(2023, 2, 9, 14, 58, 22, 91, DateTimeKind.Local).AddTicks(9039),
                            License = "07041d870811cccd5a93a5a012970b341d168b9a",
                            WhiteListed = true
                        });
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterModel", b =>
                {
                    b.HasOne("Shared.Models.Database.AccountModel", null)
                        .WithMany("Character")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedComponentModel", b =>
                {
                    b.HasOne("Shared.Models.Database.AccountCharacterModel", null)
                        .WithMany("PedComponent")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedFaceModel", b =>
                {
                    b.HasOne("Shared.Models.Database.AccountCharacterModel", null)
                        .WithMany("PedFace")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedHeadDataModel", b =>
                {
                    b.HasOne("Shared.Models.Database.AccountCharacterModel", null)
                        .WithOne("PedHeadData")
                        .HasForeignKey("Shared.Models.Database.AccountCharacterPedHeadDataModel", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedHeadModel", b =>
                {
                    b.HasOne("Shared.Models.Database.AccountCharacterModel", null)
                        .WithOne("PedHead")
                        .HasForeignKey("Shared.Models.Database.AccountCharacterPedHeadModel", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedHeadOverlayColorModel", b =>
                {
                    b.HasOne("Shared.Models.Database.AccountCharacterModel", null)
                        .WithMany("PedHeadOverlayColor")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedHeadOverlayModel", b =>
                {
                    b.HasOne("Shared.Models.Database.AccountCharacterModel", null)
                        .WithMany("PedHeadOverlay")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPedPropModel", b =>
                {
                    b.HasOne("Shared.Models.Database.AccountCharacterModel", null)
                        .WithMany("PedProp")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Database.AccountCharacterPositionModel", b =>
                {
                    b.HasOne("Shared.Models.Database.AccountCharacterModel", null)
                        .WithOne("Position")
                        .HasForeignKey("Shared.Models.Database.AccountCharacterPositionModel", "ChatacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
